### ISSUE TITLE
Interval of nearables onRange Callback

### ISSUE THREAD

**Issue by may191** [evothings/phonegap-estimotebeacons#103]
I am using: 

estimote.nearables.startRangingForIdentifier();

To monitor the accelerometer data associated with an estimote sticker.  I can modifying the advertising interval of the stickers between 100 and 5000 ms using the iOS SDK example app.  However the onRange callback seems to fire consistently at 1000ms regardless of broadcasting interval set on the nearable.

Is there any way to to modify the interval of this callback?

**Comment by heypiotr** [comment]
Piotr from Estimote here. We don't currently provide this level of customization in our native iOS SDK, so there's no way for the authors of this Phonegap plugin to implement it. However, we've been hearing this feedback a lot, and so we're considering making the ranging interval customizable.

Just to learn a little bit more about your use case: why do you need it to be more frequent than one second?

**Comment by may191** [comment]
Thanks heypiotr,  I had built an app where I stuck estimotre stickers to the tips and tails of each my downhill skiis. Then my phone recording the readings from a race run, along with temperature of the snow.   Works quite well but I noticed 2 things. 1- The accelerometers look like they max out a 2000 per axis?  And the data intervals were short for doing any reasonable analysis of the runs.

**Comment by heypiotr** [comment]
Probably best if we move this conversation to Estimote forums:
https://forums.estimote.com

(or you can ping me directly to piotr@estimote.com)
