### ISSUE TITLE
Crash on iPhone 5s / iOS 7.1

### ISSUE THREAD

**Issue by gorzny** [evothings/phonegap-estimotebeacons#23]
Hello,

Thanks for all your work. We've been following your progress on the development. I've added this plugin to my project, and ran it via xcode. I'm getting the error displayed in the screenshot.
 Is this an XCODE error due to the latest version? 

![screen shot 2014-03-20 at 10 05 35 am](https://f.cloud.github.com/assets/5174587/2472690/32fe6f9a-b039-11e3-81d4-c9c0fdc84f74.png)

I am using:
iPhone 5s IOS 7.1
Xcode 5.1
Current plugin - march 20 (from repo)

I am successfully adding the plugin to phonegap, and building for IOS. Not build errors in xcode until i run it on the device. The app crashes at this point (see screenshot).

I'm not an expert at xcode, so please be patient. :)

Thank you!

**Comment by divineprog** [comment]
Closing this issue for now, let me know if this problems remains in the updated plugin.
