### ISSUE TITLE
PhoneGap:Build support

### ISSUE THREAD

**Issue by atuttle** [evothings/phonegap-estimotebeacons#24]
I would love to be able to use this with an app on [PhoneGap:Build](https://build.phonegap.com/). I hate building locally.

It sounds like plugman is working for you, so maybe it's as simple as [submitting it](https://build.phonegap.com/plugins/add)? If you need help, let me know. I'll do my best!

**Comment by divineprog** [comment]
Closing issue since it seems to be inactive.
