### ISSUE TITLE
Notification example

### ISSUE THREAD

**Issue by homerokzam** [evothings/phonegap-estimotebeacons#33]
Do you have a notification example?

**Comment by divineprog** [comment]
@homerokzam Any news on this issue? Any progress made?

**Comment by homerokzam** [comment]
Thank you, but I'm now using Xamarin for development.

**Comment by divineprog** [comment]
@homerokzam Thanks for the update! Just post again if anything turns up.

**Comment by divineprog** [comment]
Local background notifications are available using this plugin: https://github.com/katzer/cordova-plugin-local-notifications Please see documentation in that plugin.
