### ISSUE TITLE
getBeacons receive same proximityUUID - how change this parameter when launching virtual beacon?

### ISSUE THREAD

**Issue by kotromeo** [evothings/phonegap-estimotebeacons#36]
getBeacons receive same proximityUUID - how change this parameter when launching virtual beacon?
each time when i launch virtual beacon with major, minor and id, i receive same beacons with proximityUUID = B9407F30-F5F8-466E-AFF9-25556B57FE6D and i don't see here parameter id!

**Comment by divineprog** [comment]
@ kotromeo Support for this added by this pull request: https://github.com/evothings/phonegap-estimotebeacons/pull/58

**Comment by divineprog** [comment]
Here is some documentation: https://github.com/evothings/phonegap-estimotebeacons/wiki/Virtual-beacons

**Comment by divineprog** [comment]
Documentation now also available in file documentation.md
