### ISSUE TITLE
Not all beacons are discovered everytime

### ISSUE THREAD

**Issue by mletynski** [evothings/phonegap-estimotebeacons#40]
Hi,
I just got my beacons and i'm playing with this phonegap example. I saw that from time to time not all my beacons are discovered. Some times it only discover one or two. I would say its one per ten times. Beacons are placed next to each other  (1-2 meters from my phone). Is it expected behaviour ? I have too old phone ? (iphone 4s). Is it connected with too frequent ranging ? Or maybe i should play with startEstimoteBeaconsDiscoveryForRegion method ?
Please advice !

**Comment by divineprog** [comment]
Closing this issue, let me know if to reopen in case problem persists in the updated plugin.
