### ISSUE TITLE
Virtual beacon support

### ISSUE THREAD

**Issue by murej** [evothings/phonegap-estimotebeacons#47]
Hey, is there any way to use create a virtual beacon using this plugin? The `startVirtualBeacon` function is commented out, but I can't find any explanation what that means. I've naively removed the comments for it from the in `EstimoteBeacons.js` as well as `EstimoteBeacons.h`, but I guess it's not enough.

I'm happy to contribute with a little guidance to make it work or at least to get a HELL NO from one of the devs. Thanks!

**Comment by divineprog** [comment]
Related info in this issue: https://github.com/evothings/phonegap-estimotebeacons/issues/36

**Comment by divineprog** [comment]
@murej Support for for virtual beacons added by this pull request: https://github.com/evothings/phonegap-estimotebeacons/pull/58

Note that the function names are different now (startAdvertisingAsBeacon, stopAdvertisingAsBeacon).

**Comment by divineprog** [comment]
Documentation available in file documentation.md
