### ISSUE TITLE
Android: notify when Bluetooth is not enabled

### ISSUE THREAD

**Issue by Sionarch** [evothings/phonegap-estimotebeacons#50]
When running one of the plugin's functions on Android while the device's Bluetooth is turned off, there is no notification about that Bluetooth needs to be turned on.

In [Estimote's Android-SDK Demo application](https://github.com/Estimote/Android-SDK/tree/master/Demos) there will be a dialogue asking whether the user wants to turn on Bluetooth, when a function requiring this is run, e.g. when running its "Distance Demo" activity, which shows that this functionality is available in the SDK.

**Comment by divineprog** [comment]
There is now a JavaScript function available on iOS and Android for checking the Bluetooth state. It displays a dialog to turn Bluetooth on if it is off.

Here is a code example:

    estimote.bluetoothState(
        function(result) {
            console.log('Bluetooth state: ' + result) },
        function(errorMessage) {
            console.log('Error: ' + errorMessage) })

Closing issue, let me know if to reopen.
