### ISSUE TITLE
Access other properties from iBeacons

### ISSUE THREAD

**Issue by SMJ93** [evothings/phonegap-estimotebeacons#51]
Hi, in your documentation.md files it states what can be access in iOS and Android.

Is there a way to access the other ESTBeacon classes shown here?
https://estimote.github.io/iOS-SDK/Classes/ESTBeacon.html#//api/name/delegate

If not, do you plan on including them in future versions?

Cheers

**Comment by divineprog** [comment]
Closing issue since it is not really addressing a specific need/issue. Let me know if to reopen.
