### ISSUE TITLE
startRangingBeaconsInRegion returns error "Invalid action"

### ISSUE THREAD

**Issue by chcnetconsulting** [evothings/phonegap-estimotebeacons#55]
Hello,

Help is appreciated!

I have the problem, that the plugin does not work at all - it keeps returning Invalid action when called like this:
<code>
	EstimoteBeacons.startRangingBeaconsInRegion(
		{}, // region - hier könnte man die zu empfangenden Beacons einschränken
		startRangingBeaconsInRegionCallback,
		onError
		);
</code>

I also built the beacon-finder to verify, whether it is my code that is making problems, but this also doesn't work..

Any hints?

Kind regards
Christoph

**Comment by chcnetconsulting** [comment]
BTW: I am building the android version

**Comment by chcnetconsulting** [comment]
I have found the bug :)
in EstimoteBeacons.js instead of beacons_startRangingBeaconsInRegion it is necessary to call only startRangingBeaconsInRegion... then beacons are discovered :)

**Comment by sslotsky** [comment]
I'm having this same issue, is the fix recommended by @chcnetconsulting the correct way to go? If so, should a pull request be made?

**Comment by sslotsky** [comment]
Note that I attempted to make this change in my local copy of EstimoteBeacons.js and now the app crashes when I execute ```EstimoteBeacons.startRangingBeaconsInRegion```

**Comment by divineprog** [comment]
Hi everyone,

Thanks for reporting and helping out on this. 

When updating the API for iOS the callbacks were renamed. I forgot to do this in the Android native code. Will do this right away and commit.

Very sorry for the problems this has caused you!

Mikael

**Comment by divineprog** [comment]
Hi again,

Fixed this bug now, tested on Android.

The updated code is committed here:

https://github.com/divineprog/phonegap-estimotebeacons

Made a pull request, when merged the main repo will also have the updates:

https://github.com/evothings/phonegap-estimotebeacons/pull/58

**Comment by sslotsky** [comment]
The issue does not appear to be resolved.

I tried recloning this project and rebuilding the sample app. I added an ```alert(errorMessage);``` in the ```onError``` function on line 122 of ```app.js```. Once again I received the "Invalid Action" message. I tried removing and reinstalling the plugin, but got the same result.

I also tried updating the plugin in an Ionic app that I'm trying to plug this into. Rather than the "Invalid Action" message, my sample app simply crashes when it attempts to execute ```EstimoteBeacons.startRangingBeaconsInRegion```. This is the same thing I was experiencing when I originally attempted the change suggested by @chcnetconsulting  

Let me know if you want me to put my sample app on Github and link you to the failure.

**Comment by sslotsky** [comment]
https://github.com/sslotsky/treasureHunt/blob/master/www/js/services.js#L11

**Comment by chcnetconsulting** [comment]
Hello - there is kind of a caching active in cordova/phonegap. You need to completely deinstall that plugin, clean the cache, and then reinstall from github that plugin. 


Mit freundlichen Grüßen

CHCNET Hosting & Coding
Christoph Christ
Am Röhrgraben 2
A.2410 Hainburg/Donau

Tel: +43-2165-93059
Fax: +43-2165-93059 - 339
Mobil: +43-664-9307044

UID-Nr: ATU61214947
email: 
office@chcnet.at

**Comment by sslotsky** [comment]
Thanks @chcnetconsulting 

I uninstalled the plugin using ```cordova rm pl.makingwaves.estimotebeacons``` and I reinstalled from github. I was not aware of a cache though, and searching Google hasn't yet given me a result explaining how to clear it. Can you past a link or a command?

**Comment by chcnetconsulting** [comment]
Hi

All magic cordova scripts are under platforms/android/cordova - there is also a clean script you could try. If that doesn’t help, try to update: cordova platform update android -> that also cleans the project. If nothing helps, you could try to do a „cordova platform rm android“ and „cordova platform add android“, that will recreate everything for sure :)

(if you have custom icons installed in your android folder take care, to create a backup before killing the folder).

Mit freundlichen Grüßen

CHCNET Hosting & Coding
Christoph Christ
Am Röhrgraben 2
A.2410 Hainburg/Donau

Tel: +43-2165-93059
Fax: +43-2165-93059 - 339
Mobil: +43-664-9307044

UID-Nr: ATU61214947
email: 
office@chcnet.at

**Comment by sslotsky** [comment]
I tried all your suggestions but I'm getting the same errors. "Invalid Action" for the sample app in this repo, and then a total crash for my Ionic app.

To be clear, here's what I did.

```
cordova plugin rm pl.makingwaves.estimotebeacons
cordova platform rm android
cordova plugin add https://github.com/evothings/phonegap-estimotebeacons.git
cordova platform add android
cordova build android
cordova emulate android
```

It's worth noting that before I did any of this, I saw no evidence whatsoever of the old files. Both in the ```platforms``` and ```plugins``` folders, I saw the updated version of the code, as I still do.

**Comment by chcnetconsulting** [comment]
In my app its working perfectly…

try to check the date of these files in your project folder:

./platforms/android/ant-build/classes/com/evothings/EstimoteBeacons$1.class
./platforms/android/ant-build/classes/com/evothings/EstimoteBeacons$2.class
./platforms/android/ant-build/classes/com/evothings/EstimoteBeacons$3.class
./platforms/android/ant-build/classes/com/evothings/EstimoteBeacons$PluginMonitoringListener.class
./platforms/android/ant-build/classes/com/evothings/EstimoteBeacons$PluginRangingListener.class
./platforms/android/ant-build/classes/com/evothings/EstimoteBeacons.class

These should be the compiled plugin….

**Comment by sslotsky** [comment]
The date is from this morning, as I expected. When I did ```cordova platform rm android``` it cleared the ```platforms```folder.

**Comment by sslotsky** [comment]
Keep in mind that my initial approach was to completely delete the ```phonegap-estimotebeacons``` folder and completely re-clone it. So having my old build files in there doesn't seem possible.

**Comment by sslotsky** [comment]
Going to make a minor correction to the description of my issue.

```startRangingBeaconsInRegion``` crashes my app.

```startScanningBeaconsInRegion``` gives me the "Invalid Action" error message.

This is true for both the sample app in this repo and the Ionic app that I'm trying to build.

There were copies of ```EstimoteBeacons.java``` in a ```/tmp/plugman/git``` folder. I deleted that folder completely, deleted the ```phonegap-estimotebeacons``` directory completely, re-cloned the project, and followed the instruction for adding the plugin and building on Android. I still get the errors mentioned above.

**Comment by divineprog** [comment]
@sslotsky Hi, I have some ideas.

Is it possible for you to get a stack trace of the crash that happens with startRangingBeaconsInRegion. What does your call look like? I mean the parameters given to startRangingBeaconsInRegion. There could be a bug in there, some parameters might not have been tested.

Scanning is not available on Android, so this should be why you get "Invalid Action" when calling startScanningBeaconsInRegion.

If you give me some more details about the parameters you send to startRangingBeaconsInRegion, some code snippet if possible, I will try to help.

As for the Cordova caching problems, one thing to try is to create a new Cordova project fresh and compare to see if the problem persists. 

Best, Mikael

**Comment by sslotsky** [comment]
@divineprog please see here https://github.com/sslotsky/treasureHunt/blob/master/www/js/services.js#L11

I don't have a stack trace. I'm very new to Android development so I'm not even sure where to get one. I tried to emulate using the -s and -c options but did not get any output to my console.

**Comment by sslotsky** [comment]
@divineprog also note that this error is occuring with the beacon-finder example app in this repo, completely unmodified.

**Comment by divineprog** [comment]
@sslotsky Thanks for the pointer to your code. I can see now, that as you say there are no special parameters. I have not experienced this crash myself. To see the log wpuld be helpful, here is how,

You can view Android log output with this command:

    adb logcat

Enter this in a command window ("adb" is short for Android Debug Bridge). If the adb command is not on the system path, you can add it to the path, use the full path when giving the command, or go to the folder where adb is located. It is found in the Android SDK installation. On my machine (OS X) it is in:

    android/sdk/platform-tools/adb

It would be helpful to see the log at the point of the crash. 

Are you running this in the Android emulator? Also on devices? Is behaviour the same on all devices you have tested?

**Comment by sslotsky** [comment]
Thanks, got some yummy stacktrace goodness for you. As for your last question, so far I've only run this on the emulator.

```
I/EstimoteBeacons( 1657): initialize
I/EstimoteBeacons( 1657): startRangingBeaconsInRegion
I/EstimoteBeacons( 1657): connect
I/EstimoteSDK( 1657): com.estimote.sdk.service.BeaconService.onCreate:186 Creating service
E/BluetoothAdapter( 1657): Bluetooth binder is null
I/EstimoteBeacons( 1657): onServiceReady
I/EstimoteBeacons( 1657): startRanging
W/dalvikvm( 1657): threadid=18: thread exiting with uncaught exception (group=0xb1cc4b20)
D/gralloc (  926): Registering a buffer in the process that created it. This may cause memory ordering problems.
E/libEGL  (  926): called unimplemented OpenGL ES API
E/libEGL  (  926): called unimplemented OpenGL ES API
E/libEGL  (  926): called unimplemented OpenGL ES API
E/libEGL  (  926): called unimplemented OpenGL ES API
E/SurfaceFlinger(  926): glCheckFramebufferStatusOES error -657267111
E/SurfaceFlinger(  926): got GL_FRAMEBUFFER_COMPLETE_OES error while taking screenshot
E/libEGL  (  926): called unimplemented OpenGL ES API
E/libEGL  (  926): called unimplemented OpenGL ES API
D/CordovaActivity( 1657): Paused the application!
D/CordovaWebView( 1657): Handle the pause
E/AndroidRuntime( 1657): FATAL EXCEPTION: BeaconServiceThread
E/AndroidRuntime( 1657): Process: com.evothings.beaconfinder, PID: 1657
E/AndroidRuntime( 1657): java.lang.NullPointerException: Bluetooth adapter cannot be null
E/AndroidRuntime( 1657): 	at com.estimote.sdk.internal.Preconditions.checkNotNull(Preconditions.java:21)
E/AndroidRuntime( 1657): 	at com.estimote.sdk.service.BeaconService.startRanging(BeaconService.java:232)
E/AndroidRuntime( 1657): 	at com.estimote.sdk.service.BeaconService.access$1200(BeaconService.java:62)
E/AndroidRuntime( 1657): 	at com.estimote.sdk.service.BeaconService$IncomingHandler$1.run(BeaconService.java:473)
E/AndroidRuntime( 1657): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 1657): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 1657): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 1657): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/ActivityManager( 1137):   Force finishing activity com.evothings.beaconfinder/.CordovaApp
W/WindowManager( 1137): Screenshot failure taking screenshot for (246x410) to layer 21010
D/dalvikvm( 1137): GC_FOR_ALLOC freed 69K, 11% free 5611K/6280K, paused 10ms, total 10ms
I/dalvikvm-heap( 1137): Grow heap (frag case) to 6.159MB for 635808-byte allocation
D/dalvikvm( 1137): GC_FOR_ALLOC freed 4K, 10% free 6228K/6904K, paused 29ms, total 29ms
D/dalvikvm( 1137): GC_CONCURRENT freed 19K, 9% free 6298K/6904K, paused 11ms+20ms, total 54ms
D/ConnectivityService( 1137): [CheckMp] isMobileOk: not connected ni=NetworkInfo: type: mobile_hipri[UMTS], state: DISCONNECTED/IDLE, reason: (unspecified), extra: (none), roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false
D/CordovaActivity( 1657): CordovaActivity.onDestroy()
D/CordovaWebView( 1657): >>> loadUrlNow()
I/EstimoteBeacons( 1657): onDestroy
I/EstimoteSDK( 1657): com.estimote.sdk.service.BeaconService.onDestroy:209 Service destroyed
D/ConnectivityService( 1137): [CheckMp] isMobileOk: not connected ni=NetworkInfo: type: mobile_hipri[UMTS], state: DISCONNECTED/IDLE, reason: (unspecified), extra: (none), roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false
I/Process ( 1657): Sending signal. PID: 1657 SIG: 9
I/ActivityManager( 1137): Process com.evothings.beaconfinder (pid 1657) has died.
W/Binder  ( 1369): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 1369): java.lang.NullPointerException
W/Binder  ( 1369): 	at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
W/Binder  ( 1369): 	at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
W/Binder  ( 1369): 	at android.os.Binder.execTransact(Binder.java:404)
W/Binder  ( 1369): 	at dalvik.system.NativeStart.run(Native Method)
E/SoundPool( 1137): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService( 1137): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool( 1137): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService( 1137): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool( 1137): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService( 1137): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool( 1137): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService( 1137): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool( 1137): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService( 1137): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool( 1137): error loading /system/media/audio/ui/KeypressStandard.ogg
W/AudioService( 1137): Soundpool could not load file: /system/media/audio/ui/KeypressStandard.ogg
E/SoundPool( 1137): error loading /system/media/audio/ui/KeypressSpacebar.ogg
W/AudioService( 1137): Soundpool could not load file: /system/media/audio/ui/KeypressSpacebar.ogg
E/SoundPool( 1137): error loading /system/media/audio/ui/KeypressDelete.ogg
W/AudioService( 1137): Soundpool could not load file: /system/media/audio/ui/KeypressDelete.ogg
E/SoundPool( 1137): error loading /system/media/audio/ui/KeypressReturn.ogg
W/AudioService( 1137): Soundpool could not load file: /system/media/audio/ui/KeypressReturn.ogg
E/SoundPool( 1137): error loading /system/media/audio/ui/KeypressInvalid.ogg
W/AudioService( 1137): Soundpool could not load file: /system/media/audio/ui/KeypressInvalid.ogg
W/AudioService( 1137): onLoadSoundEffects(), Error -1 while loading samples
W/InputMethodManagerService( 1137): Got RemoteException sending setActive(false) notification to pid 1657 uid 10054
```

**Comment by divineprog** [comment]
Hi, thanks for the log!

Here is where it goes wrong:

    E/AndroidRuntime( 1657): java.lang.NullPointerException: Bluetooth adapter cannot be null
        E/AndroidRuntime( 1657):    at com.estimote.sdk.internal.Preconditions.checkNotNull(Preconditions.java:21)
        E/AndroidRuntime( 1657):    at com.estimote.sdk.service.BeaconService.startRanging(BeaconService.java:232)

This happens in the Estimote Android library, and I suspect this is because Bluetooth is not available /or not turned on) in the emulator. Do other Bluetooth apps run in the emulator?

Will look into preventing and reporting this error in the Android plugin, so at least the app won't crash. Also Bluetooth could be requested to be turned on if off, will investigate further to add this.

**Comment by sslotsky** [comment]
Thanks @divineprog that makes plenty of sense and I should have considered it when trying to execute bluetooth functionality on an emulator with no bluetooth capabilities!

I will have to test it on the physical device then. I got so caught up in errors occurring in the emulator that I didn't even bother to try it. Like I said, Android dev n00b here :-)

**Comment by divineprog** [comment]
@sslotsky You are welcome anytime :) Let me know how it goes. Happy hacking :-)
