### ISSUE TITLE
Terminating app: Range Beacons and Monitor Regions

### ISSUE THREAD

**Issue by rblakeley** [evothings/phonegap-estimotebeacons#56]
I'm running the example on my iPhone from terminal. The "Scan Beacons" button is working. The "Range Nearables" button takes me to a blank screen, but the app does not terminate.

Pressing "Range Beacons" or "Monitor Regions" is terminating the app.
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CLBeaconRegion inMotion]: unrecognized selector sent to instance 0x1610fa00'
```

What's this all about?

**Comment by divineprog** [comment]
@rblakeley thanks for reporting this problem.

The error you are seem to come form the Estimote iOS SDK, the selector "inMotion" is never sent in the plugin code (just checked). Do you get any clues from the stack trace if the error happens in the SDK code or in the plugin code?

Is the "Range Nearables" screen blank like "black" or is it just not showing any stickers? 

Are you using stickers or beacons?

Best, Mikael

**Comment by kwaak** [comment]
I'm encountering the same error while doing some testing. I'm going to do some more debugging and will share if I find out anything more about this.

**Comment by rblakeley** [comment]
Thanks for the timely reply. I deleted everything and set it up again from scratch and the error went away. So I really have no clue what was causing the issue or how it was fixed.

The iPhone screen had the Ranging Beacons header and Back button, so it wasn't black. I am working with beacons (not stickers).

**Comment by divineprog** [comment]
Thanks everyone for testing, much appreciated!

**Comment by kwaak** [comment]
Well my issue was I simply called `startRangingBeaconsInRegion()` before I had location authorization.

I misinterpreted the success and error callback of `authorizationStatus()`. I did not check the result argument of the success callback correctly.

**Comment by divineprog** [comment]
@kwaak Thanks a lot for pointing out this problem. I am updating the documentation comment to be more clear about the result parameter containing the auth status.
