### ISSUE TITLE
Sample app doesn't find beacons

### ISSUE THREAD

**Issue by sslotsky** [evothings/phonegap-estimotebeacons#57]
I followed the instructions to build the beacon-finder example for Android. After the build we're supposed to enter the command

```
adb install -r platforms/android/ant-build/BeaconFinder-debug.apk
```

However, this file does not exist after building. Instead I tried using the file that was listed in the build output:

```
[echo] Debug Package: /home/sam/phonegap-estimotebeacons/examples/beacon-finder/platforms/android/ant-build/CordovaApp-debug.apk
```

This produces the message below, and sits there until I kill it manually.

```
error: device not found
- waiting for device -
```

I've also tried omitting this step altogether. When I skip this and proceed with ```cordova emulate android```, the app runs, but my beacons don't show up when I click Scan. The beacons show up in the BLE scanner that I downloaded on my android phone.

Does this have anything to do with not being able to install the debug package? If not, what else might be behind this?

**Comment by knuxus** [comment]
Im on iPhone, just installed the app, it never finds anything...

And also gets stuck inside every menu, without possibility of getting back... am I missing some special config file somewhere?

**Comment by sslotsky** [comment]
I've discovered my issue is a duplicate of https://github.com/evothings/phonegap-estimotebeacons/issues/55
