### ISSUE TITLE
plugin does not work in android < 4.3

### ISSUE THREAD

**Issue by rafaelrsilva** [evothings/phonegap-estimotebeacons#59]
I have installed the latest version but it does not work on android < 4.3, the app crashes during starting. Is it compatible with this versions? The iOS version works normally.

**Comment by ardiri** [comment]
BLE support was introduced with Android 4.3.                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Rafael Ribeiro da SilvaSent: Monday, February 2, 2015 19:19To: evothings/phonegap-estimotebeaconsReply To: evothings/phonegap-estimotebeaconsSubject: [phonegap-estimotebeacons] plugin does not work in android < 4.3 (#59)I have installed the latest version but it does not work on android < 4.3, the app crashes during starting. Is it compatible with this versions? The iOS version works normally.

—Reply to this email directly or view it on GitHub.

**Comment by rafaelrsilva** [comment]
Thanks for information ardiri! It working fine in android 4.3 and 4.4.4, after i will test in android 5.0. the previous problems was really solved.
