### ISSUE TITLE
estimote.beacons.authorizationStatus asks the user to turn on Bluetooth

### ISSUE THREAD

**Issue by CookieCookson** [evothings/phonegap-estimotebeacons#67]
In older versions of the plugin, you can determine the location permission status and then act with ranging/monitoring which would cause a bluetooth dialog to display if not enabled. In the latest version of the plugin when you try to determine the location permission status it asks the user to turn on their bluetooth which can get very annoying (I check this in a backgroundFetch so the App is asking the user to turn on their bluetooth every 10 minutes or so even when not using the App!).

**Comment by divineprog** [comment]
I am not sure if this is something that has changed in iOS or is caused by the plugin implementation (or by the Estimote iOS library).

The plugin does not explicitly ask for turning on Bluetooth (as far as I can recall).

What is the desired behaviour?

**Comment by CookieCookson** [comment]
The behaviour works as intended on the older versions of the plugin (I was using 0.4.X previously), but when executing estimote.beacons.authorizationStatus on the newer versions of the plugin the App will ask the user to turn on Bluetooth if it is not enabled. Surely checking the location authorisation status should not require Bluetooth?

**Comment by divineprog** [comment]
Hi, I did some further testing and I get the same result as you do. Build a native iOS app and called:

    [CLLocationManager authorizationStatus];

which does not display the Bluetooth message.

Possible the Estimote SDK does some call that causes the dialog to display. 

The plugin does nothing special, just calling the SDK:

    [ESTBeaconManager authorizationStatus];

https://github.com/evothings/phonegap-estimotebeacons/blob/master/plugin/src/ios/EstimoteBeacons.m#L811

Not sure how to solve this and make the dialog not display. Any ideas anyone?
