### ISSUE TITLE
Does this plugin support Secure UUID

### ISSUE THREAD

**Issue by AndreaBruno** [evothings/phonegap-estimotebeacons#68]
Hi,

Does this plugin support Secure UUID, as described in the link below?
https://community.estimote.com/hc/en-us/articles/204233603-How-security-feature-works

Thank you,

Andrea

**Comment by divineprog** [comment]
Hi, yes this is supported. 

Here is documentation:

https://github.com/evothings/phonegap-estimotebeacons/blob/master/documentation.md#secure-beacons-ios
