### ISSUE TITLE
Possible to get this into build.phonegap.com?

### ISSUE THREAD

**Issue by jhberges** [evothings/phonegap-estimotebeacons#69]
That'd be really nice! :-)

*Edit* : I tried adding it as a private plugin, but it seems someone else has had the same idea - and the ID is already in use :-/

**Comment by kwaak** [comment]
I have this plugin as a private plugin in phonegap build.

![image](https://cloud.githubusercontent.com/assets/220656/6504872/2a6a9234-c33c-11e4-8b57-3fc530f1ef5d.png)

Does this really prevent you from also adding it as a private plugin doe to the same ID? That's very strange.

**Comment by jhberges** [comment]
Hi, and thanks for getting back.

Yes - it seems that plugin-IDs are global across both public and private scopes  :-/

The solution for me was to fork your repo, prefix the ID and add it as a private plugin.
Quite daft, I agree

**Comment by kwaak** [comment]
Yeah, that's the solution I was thinking of aswell.

It's a known PB issue: https://github.com/phonegap/build/issues/408

Btw, not my repo, just a user aswell.

**Comment by divineprog** [comment]
Closing issue, let me know if to reopen.
