### ISSUE TITLE
generic ibeacon plugin

### ISSUE THREAD

**Issue by darrenahunter** [evothings/phonegap-estimotebeacons#70]
Hi 
are there any plans to pull out the generic ibeacon api's from this plugin to create a more simple plugin for use with any ibeacon that conforms to the standard.
no will this plugin also work with non 'estimote' beacons as well.

thanks
Darren

**Comment by divineprog** [comment]
Hi, you can for example use this plugin:

https://github.com/petermetz/cordova-plugin-ibeacon

It is a generic iBeacon plugin that works with Estimote Beacons.

**Comment by darrenahunter** [comment]
Thank you for your reply

Yes I have been evaluating Peter’s plugin also. It just has a few issues and Peter is not as actively maintaining it as he would like - pretty busy on other work at the moment. I was just looking around for a more maintained generic plugin.

I gather this plugin is very estimate specific

thanks again

Darren
