### ISSUE TITLE
Bluetooth dialog on Android

### ISSUE THREAD

**Issue by divineprog** [evothings/phonegap-estimotebeacons#72]
**Problem**

On Android not Bluetooth dialog is displayed if Bluetooth is turned off.

See this forum thread for details: http://evothings.com/forum/viewtopic.php?t=1404

**Solution**

Add this to the Android plugin:

"On Android, you need to include this pop-up windows into the app yourself. We have an example for this in our SDK: https://github.com/Estimote/Android-SDK/blob/master/Demos/src/main/java/com/estimote/examples/demos/ListBeaconsActivity.java#L111"

**Comment by engbmsdev** [comment]
+1

Another solution could be to use [BluetoothSerial Plugin](https://github.com/don/BluetoothSerial) with methods `bluetoothSerial.isEnabled`, `bluetoothSerial.showBluetoothSettings` and/or `bluetoothSerial.enable`

**Comment by divineprog** [comment]
Implemented by this pull request: https://github.com/evothings/phonegap-estimotebeacons/pull/74 and commit: https://github.com/evothings/phonegap-estimotebeacons/commit/73bf5a74185ab95c48e6ecd195531a9ea339c42f
