### ISSUE TITLE
Publish plugin using npm

### ISSUE THREAD

**Issue by divineprog** [evothings/phonegap-estimotebeacons#81]
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

**Comment by derulo** [comment]
Hello, can you please make a push of the latest plugin on the npm plugin registry for Phonegap Build. Thanks a lot!

**Comment by divineprog** [comment]
Thanks for pointing this out. Will look into publising the plugin.

**Comment by divineprog** [comment]
Plugin is published on npm with id: cordova-plugin-estimote
