### ISSUE TITLE
Stop monitoring ranging not working?

### ISSUE THREAD

**Issue by davorpeic** [evothings/phonegap-estimotebeacons#83]
Using version 0.7.1
ios 8.3
with angularjs app

I'm trying to stop ranging and monitoring by using
estimote.beacons.stopMonitoringForRegion({});
and
estimote.beacons.stopMonitoringForRegion({});

but I still get updates from success callback created from 
estimote.beacons.startMonitoringForRegion and estimote.beacons.startRangingBeaconsInRegion
I tried giving the same region object for stopping to, but it is the same..

My region looks like this
var CheckInRegion = {
        identifier: "CheckInRegion",
        uuid: "6A3D864B-.....",
        major: "xxxx"
    };

Do I need to do anything else? I'm working in a angulajs app with ionic.

Edit: I can confirm this is also an issue with beacon-finder example app, if I enter to ranging, then go back (its supposed to stop the ranging) I get back in ranging and I see 'Range error: null' in console log. 

thanks

**Comment by newelement** [comment]
I'm actually having this issue on Android. iOS seems to be working ok for me.

**Comment by newelement** [comment]
For Android I had to specify the range object. I could not leave it empty as I did for iOS

**Comment by davorpeic** [comment]
I will close this issue as it is fixed with the new version of the plugin after they updated to new SDK. Thanks for the tip :)
