### ISSUE TITLE
Detecting bluetooth enabled/disabled ?

### ISSUE THREAD

**Issue by rbsmidt** [evothings/phonegap-estimotebeacons#89]
Is there a way to check if bluetooth is enabled/disabled through evothings' plugin? i've tried estimote.bluetoothState as i saw it mentioned somewhere in here - but it seems to return a function. This is what i get in console:

function (success, error) {
	exec(success,
		error,
		'EstimoteBeacons',
		'bluetooth_bluetoothState',
		[]
	);

	return true;
}

I'm looking more for just a "false" or "true" to determine wether bluetooth is available or not.

Ultimately i want to prevent my app from closing down, if the user hasn't turned on bluetooth, and instead not scan for beacons - so if another function/callback is more suitable for this action, please let me know :-)

Best regards,
Rasmus

**Comment by salilsethi** [comment]
Rasmus - in the success callback look at the result variable. The result variable will have the state of bluetooth... See below as an example. Hope this helps.

estimote.bluetoothState(
    //Success function
    function(result){
      console.log('Bluetooth is active: ' + result);
    },
    //error function
    function(errorMessage){
      console.log('Bluetooth check error: ' + errorMessage);
    }
  );

**Comment by rbsmidt** [comment]
Hi salilsethi.

Thanks a lot for clearing that up, it works like a charm now. I had somehow understood, that the estimote.bluetoothState() just returned true or false like that. But using a success and error-function did the trick. Again thanks.

Maybe you should mention the function in your docs - i only came across it through another (older) issue in here, but it's really useful for me, and might be for someone else to. Just i suggestion anyways :-)

Best regards
