### ISSUE TITLE
Bitcode

### ISSUE THREAD

**Issue by davorpeic** [evothings/phonegap-estimotebeacons#98]
Hi,

I had to disable Bitcode in Xcode to be able to build the app using the plugin, is this something that could take me to Apple rejecting the app?

thanks

**Comment by 255kb** [comment]
Hi, I had no trouble getting apps accepted in the store without bitcode. 
It seems that Estimote is working on bitcode support: https://forums.estimote.com/t/estimotesdk-estbeaconmanager-o-does-not-contain-bitcode-xcode-7/1922/5

**Comment by heypiotr** [comment]
Estimote SDK 3.7.0 which we released on Monday comes with bitcode enabled (:

**Comment by davorpeic** [comment]
Ok great

thanks to both
